### ISSUE TITLE
DNS: show the TTL somehow

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#102]
It would be nice to know at times

**Comment by jesopo** [comment]
could be an issue: https://github.com/rthalley/dnspython/issues/150#issuecomment-210444606

**Comment by JinnCirce** [comment]
I suppose since it's not adhering to spec (deprecated method, without much use, as they say) to have different TTL for the same "Resource Record Set", then it could just be "lowest TTL: xxxx" as they say...with a link in the docs for the rfc, and/or the referenced issue, to avoid people making an issue out of it, maybe...

**Comment by Mikaela** [comment]
My comment from IRC:

> if I understood the link correctly, it's about it being possible that different records have different TTL even if they are of the same type, but I think that woudl be a very corner case and I would be happy with seeing just one TTL as it's safe assumption that the others would be the same. And if that is not the case, the documentation for that module could mention it as it's probably not daily that people
are wondering it

I think the "lowest" would be unnecessary word.

**Comment by JinnCirce** [comment]
> I think the "lowest" would be unnecessary word.

it should definitely be mentioned somewhere, maybe not in the output, but someplace obvious, and right now we don't have docs to put it in
if it's not mentioned then there will be people thinking it to be a bug, or suggesting it to work for multiple TTLs
different TTL times aren't *prohibited*, after all...just discouraged and deprecated...

**Comment by jesopo** [comment]
we could explore using a different DNS library that does not have this limitation?

**Comment by JinnCirce** [comment]
> we could explore using a different DNS library that does not have this limitation?

you could...but as said in the rfc, that's what should be happening anyway, and the things different TTLs could be used for an be done in other ways (not that they say how, but still)...
could be having ttl be a separate command too, and make new query for each record?

**Comment by Mikaela** [comment]
Wouldn't having TTL in separate commands double the amount of commands without a very big reason to do so?
