### ISSUE TITLE
b2sum support

### ISSUE THREAD

**Issue by trobotham** [bitbot-irc/bitbot#109]
It appears that b2sum is not supported in hash, any particular reason for this?

**Comment by jesopo** [comment]
BitBot basically passes through to python's hashlib

https://github.com/jesopo/bitbot/blob/25b507e80cb07c62f638e710728c88bd1c3b87a6/modules/hash.py#L14

That said...

```
16:33 <jesopo> ,hash blake2b test
16:33 <+BitBot> [Hash] test -> a71079d42853dea26e453004338670a53814b78137ffbed07603a41d76a483aa9bc33b582f77d30a65e6f29a896c0411f38312e1d66e0bf16386c86a89bea572
16:33 <jesopo> ,hash blake2s test
16:33 <+BitBot> [Hash] test -> f308fc02ce9172ad02a7d75800ecfc027109bc67987ea32aba9b8dcc7b10150e
```

**Comment by jesopo** [comment]
added functionality to show available hash algorithms https://github.com/jesopo/bitbot/commit/06b41cb30efa8aadc4a748ff83116cf860e82352
