### ISSUE TITLE
`to` command doesn't error on impossible target nick

### ISSUE THREAD

**Issue by JinnCirce** [bitbot-irc/bitbot#111]
some people would expect `to * test` to match all people in channel, and can be confusing when it successfully saves message, but never sends it
it even works with impossible nicks, such as `thisnickwillnev€rexist+so*just-testinäg`...
to sum up, verify target nick is even possible :)

**Comment by jesopo** [comment]
this is actually not totally straight forward. deciding what is and is not a valid nickname is up to the server. there's some obvious ones (`!`, `@`, `:`) but an exhaustive list would be hard. `*` isn't always going to be forbidden on every server.

**Comment by jesopo** [comment]
what I could do is restrict it to nicknames that bitbot has seen active at some point!
