### ISSUE TITLE
ducks are not synced properly to account

### ISSUE THREAD

**Issue by RyanSquared** [bitbot-irc/bitbot#116]
@jesopo should know what this issue is

**Comment by jesopo** [comment]
seen this happen only on freenode thus far - looks like bitbot loses track of `identified_account_id_override` somehow, thus settings go against given nickname instead of nickserv account

**Comment by jesopo** [comment]
I think the correct way forward here might actually be revamping how we transparently switch between which nickname we look for settings under. This is quite hacky:
https://github.com/jesopo/bitbot/blob/fc765228ebe65387298ee7d71284776159baeb31/src/IRCUser.py#L38-L42

**Comment by jesopo** [comment]
this seems to be a freenode-specific (or maybe chary-derived) problem
