### ISSUE TITLE
Feature request: (unix) ping command

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#120]
for getting the stats out

```
--- example.com ping statistics ---
10 packets transmitted, 10 packets received, 0% packet loss
round-trip min/avg/max/stddev = 124,285/132,818/156,479/10,110 ms
```

**Comment by jesopo** [comment]
rationale?

**Comment by jesopo** [comment]
would it also be acceptable to just write a module that checks if a given ip/host is "up"? we've got `isup.py` already but that's http-based so I could write something a lot lower down

**Comment by Mikaela** [comment]
Sure, I guess

**Comment by jesopo** [comment]
i ask because parsing the output of the ping command is

1. trying to parse human-readable format
2. output can change

and I'm very unhappy about both of those
