### ISSUE TITLE
net.ipv6.bindv6only=1 causes the port to be IPv6 only

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#124]
Limnoria fix I think: https://github.com/ProgVal/Limnoria/commit/a39238aba9489ef69fa4f7d545502a4049ac1953

**Comment by jesopo** [comment]
I'll most likely be switching to Tornado's HTTP server instead of just directly fixing this - two birds with one stone as the python stdlib http server is not meant for production environments

**Comment by Mikaela** [comment]
The port turned localhost only and needs a reverse proxy, so closing

**Comment by jesopo** [comment]
this isn't an issue now that the REST API requires something akin to nginx proxy_pass in front of it.
