### ISSUE TITLE
Feature request: apropos command

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#133]
Limnoria and shell have command `apropos` for searching commands, I think it would be helpful at times with bitbot.

`Searches for <string> in the commands currently offered by the bot, returning a list of the commands containing that string.`

**Comment by jesopo** [comment]
I think a better way of tackling this might be to add a list of "confusable" commands for each command. if you try to use a command that's in a command's "confusables" list, it will recommend the real command to you.

"grabquote" could be in "quotegrab"'s confusables list, e.g.
