### ISSUE TITLE
Option to write a PID file or somehow make the certificates programmetically reloadable

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#140]
Currently I have told my script to install acme.sh certificates to `systemctl restart bitbot --quiet` as the command to reload the certificate and I don't know how to get the PID for sending a SIGUSR1 or whichever the flag for it was, so my bitbot restarts nightly at midnight and I would like to fix that behaviour.

**Comment by jesopo** [comment]
is this for the REST API or for the bot's client-side certificates for IRC connections?

**Comment by Mikaela** [comment]
The REST API

**Comment by Mikaela** [comment]
Would there be any point in making the systemd service do `ExecReload=/bin/kill -USR1 $MAINPID` or is there SIGHUP or similar to do something else?

**Comment by Mikaela** [comment]
Invalid

```
2019-09-13T00:46:55+0300 <jesopo> i do not believe SIGUSR1 reloads certificates
2019-09-13T00:46:58+0300 <jesopo> SIGHUP does though
```
