### ISSUE TITLE
Feature request: allow YouTube address to be configurable

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#141]
It would be nice to be able to point the bot into giving invidio.us or similar addresses instead of youtube.com

**Comment by jesopo** [comment]
not sure what the benefits of this are - I'd assume the people wanting to use a youtube alt are few enough that they'd have some kind of mechanism in their browsers to do this kinda magic for them?

**Comment by Mikaela** [comment]
I think the main benefit would be not sending the data to Google directly and possibly not seeing advertisements. I don't know how many people there are using it, but I have been changing youtube.com to invidio.us by hand on desktop and I think there would be problems with browser mechanism especially on mobile.

**Comment by jesopo** [comment]
Might just implement this as outbound text replacement rules so that any youtube URL that comes out of the bot is rewritten just before hitting the wire. means any module that tries to send out a youtube URL will have it automatically changed.

means the module that does this isn't youtube-specific and can be used for all sorts of things

**Comment by Mikaela** [comment]
That would be nice and also allow redirecting twitter.com to nitter.net

**Comment by jesopo** [comment]
work for this done as of jesopo/bitbot@8153047f by server-wide filters:

`!filter add s/youtube.com/invidio.us/g`
`!filter add s/twitter.com/nitter.net/g`

(`g` flag isn't support yet but will be soon)

**Comment by jesopo** [comment]
`g` flag is now supported

**Comment by jesopo** [comment]
closing as I believe this has been satisfied. let me know if you disagree
