### ISSUE TITLE
split command output at a more user-readable place

### ISSUE THREAD

**Issue by jesopo** [bitbot-irc/bitbot#159]
Currently will happily cut words in half. Would be nicer to split at the closest word end.

**Comment by panicbit** [comment]
I'll try to take care of this.

**Comment by jesopo** [comment]
Advice would be

https://github.com/jesopo/bitbot/blob/5aba3f509e6e7a88f9ae6efc1735729297fa1701/modules/commands/outs.py#L53-L54

Check the first char of `truncated` - if it's a valid "word end" then do nothing. Otherwise, track backwards from the end of `valid` to find the first valid "word end" and split there - then prepend the split off stuff to `truncated`.

hope that makes sense!
