### ISSUE TITLE
You can catch ducks before they quack

### ISSUE THREAD

**Issue by Eijebong** [bitbot-irc/bitbot#177]
So with the delay added, you can catch a duck between the time it's triggered by a message and the time it quacks in the channel.

**Comment by Emerentius** [comment]
I approve of this feature.

Edit: @panicbit made me change my mind.

**Comment by panicbit** [comment]
This sounds more like a bug than a feature to me.

**Comment by jesopo** [comment]
the criteria by which `!bef` checks if there's a duck to catch is based on this var
https://github.com/jesopo/bitbot/blob/ea589b744ff26d95c9933c03b6068c55b945c97e/modules/ducks.py#L57
this var is being set when the timer starts, not when it's finished.
