### ISSUE TITLE
Coins module cache sometimes bugs out leading to negative delta

### ISSUE THREAD

**Issue by MineRobber9000** [bitbot-irc/bitbot#205]
For example: (before this, I had last redeemed 13:08)

```
13:18 < khuxkm> ,redeemcoins
13:18 < BitBot> [Coins] khuxkm: Please wait -1w 6d 23h 59m 45s before redeeming
```

Not sure if this is an issue with the cache or the module.

**Comment by jesopo** [comment]
will look in to it. cheers!

**Comment by jesopo** [comment]
this is almost certainly an issue with `src/Cache.py` - that's what tracks how long it's been since you redeemed coins

**Comment by jesopo** [comment]
jesopo/bitbot@bc6b1dda47b4076b7280c9729ff139a7cbac4ecb might fix this. not certain yet

**Comment by jesopo** [comment]
@MineRobber9000 have you seen this issue recently?

**Comment by MineRobber9000** [comment]
Not recently, no.
