### ISSUE TITLE
karma increment message should include the current karma total

### ISSUE THREAD

**Issue by slingamn** [bitbot-irc/bitbot#214]
As discussed in #bitbot: the new-style karma messages print the total karma granted to bob by alice, but don't print bob's total karma. Ideally there'd be language that could include both values.

**Comment by jesopo** [comment]
I agree - however we now permit self-karma and that doesn't factor in to total karma so wording has to cover:

- how much karma per-user is given
- total karma
- the fact that self-karma doesn't effect totals

it's hard to find perfect language for this

**Comment by jesopo** [comment]
given a shot at improving the wording as of jesopo/bitbot@90cbc5a:

```
17:21 <jesopo> jesopo++
17:21 <BitBot> [Karma] jesopo has given jesopo 3 karma (90 total)
```

**Comment by slingamn** [comment]
Works for me.

**Comment by jesopo** [comment]
gonna leave the card open for a bit while I gather feedback from various communities about this change

**Comment by jesopo** [comment]
seems to have been well-received.
