### ISSUE TITLE
pip3 install -r requirements.txt doesn't install python module dataclasses

### ISSUE THREAD

**Issue by TehPeGaSuS** [bitbot-irc/bitbot#215]
Using `pip3 install -r requirements.txt` doesn't install python module dataclasses which leads to `./bitbotd -a` failure.

I've had this issue after adding a shell user with _adduser bitbot_, logged in as the user, cloned the git repo, used the command to install the needed dependencies and then when using `./bitbotd -a` it thrown an error about the missing module __dataclasses__

**Comment by jesopo** [comment]
should be resolved as of jesopo/bitbot@8ebde7b1. let me know if you have any issues.
