### ISSUE TITLE
suggestion for karma message

### ISSUE THREAD

**Issue by slingamn** [bitbot-irc/bitbot#226]
Currently:

```
[06:39:16 PM] <comradeblue> bitbot++
[06:39:16 PM] -BitBot/#darwin- [Karma] comradeblue has given bitbot 1 karma (3 total)
```

but how about this message instead: `bitbot now has 3 karma (1 from comradeblue)`?

**Comment by jesopo** [comment]
love it. I'll try it out shortly

**Comment by jesopo** [comment]
will leave this issue open for a bit, just in case we decide this format isn't right either.
