### ISSUE TITLE
Github needs more colors

### ISSUE THREAD

**Issue by DarthGandalf** [bitbot-irc/bitbot#26]
E.g. in "commit by" message: +0 ∆1 -0 could be green/yellow/red. Some color for repo name, some color for org name, some color for the commiter author/email. Just to make them more visually distinct.

In the "commented"/"merged" messages, the username should be probably the same color as commiter in "commit by"

**Comment by jesopo** [comment]
As of jesopo/bitbot@a9c870e there's coloration and style changes on the added/removed/modified numbers

**Comment by jesopo** [comment]
Decided that username/author/commenter/etc parts would do best to be bold (implemented in jesopo/bitbot@251f65c0)

thoughts?

**Comment by DarthGandalf** [comment]
As long as it's visually distinct, I don't mind. I didn't see bold usernames in its output in action yet.
