### ISSUE TITLE
{Question] How do you generate "client TLS certificate" ?

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#266]
> Generate a TLS keypair and point bot.conf's tls-key to the private key and tls-certificate to the public key.

* https://github.com/jesopo/bitbot/blob/master/docs/help/config.md#configure-client-tls-certificate

I am mostly seeing this done either automagically by \<LetsEncrypt client\> or similar to [Limnoria's documentation](https://docs.limnoria.net/use/identifying_to_services.html#certfp) which results a single `.pem` file and I think the `config.md` document could be a lot more helpful if it gave the command or any pointers.

**Comment by examknow** [comment]
looks like this was done in https://github.com/jesopo/bitbot/commit/a5f29ce4c07c9e7c9c264119b5f16872a7b08c21
