### ISSUE TITLE
you cannot check the time of the north pole

### ISSUE THREAD

**Issue by xfnw** [bitbot-irc/bitbot#288]
## expected behavior
BitBot will tell you the time of the location

## observed behavior
BitBot will not respond when you check the time of the north pole.

```irc
<vulpine> time north pole
<vulpine> time south pole
-BitBot- [Time] It is 2020-11-10 12:15:28 UTC+13 in South Pole
```

this bug was found by @kiedtl a few weeks ago, but it seems he was too busy to file an issue

**Comment by fndax** [comment]
This isn't a bug.

Antarctica/South_Pole exists and is UTC +12 or +13 depending on daylight saving time, per the zoneinfo database.

The North Pole does not have permanent settlement or an assigned timezone, and therefore does not have a standardized time. See https://en.wikipedia.org/wiki/North_Pole#Time for more info.

**Comment by xfnw** [comment]
bitbot's location settings seem to disagree 
```irc
<vulpine> c u location north pole
-BitBot- [Config] Config 'location' set to {'timezone': 'GMT-12',
         'lat': 90.0, 'lon': 0.0, 'name': 'North Pole'}
```

**Comment by jesopo** [comment]
this is a problem of the reverse geocoding API we use and the timezone library we use disagreeing and im not excited about trying to explicitly exclude known-to-be-invalid timezones, but guess I'll have to

**Comment by fndax** [comment]
More specifically, it's the geocoding API spitting out GMT offsets for locations like the North Pole that don't have a zoneinfo timezone assigned to them.

If anything, the bug here is that GMT offsets are shown and stored in location config, I could see it making sense to check for and null those, but it's more of an implementation detail than anything else.

**Comment by jesopo** [comment]
this should adequately destroy this inconsistency jesopo/bitbot@8cc47a9321fab3ef5036b25ebd174633b5b041c9
