### ISSUE TITLE
,karmasho fallback if nobody added karma for a term

### ISSUE THREAD

**Issue by AntonMcClure** [bitbot-irc/bitbot#295]
If nobody added karma to something, and you use `,karmawho`, it returns the following:

```
<BitBot> [Karma] (thing) has karma from:
```

I think it would be better if the message would specify that is has no karma, like in the below examples:

```
<BitBot> [Karma] (thing) has karma from nobody.
```
```
<BitBot> [Karma] (thing) has no karma.
```

Please let me know what you think of this, and what you would like for the message to say. If you would like, I can do a pull request for this. Thanks for considering!

**Comment by examknow** [comment]
Addressed in #298
