### ISSUE TITLE
Feature request: linking multiple NickServ accounts into one BitBot account

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#325]
I have one NickServ account with more privileges and another for third party services like Matrix and IRCCloud with the least flags required for use in emergency.

I would like to link the second account to the main account so it would share the same user configuration (pronouns/timezone/etc.) and badges.

**Comment by examknow** [comment]
I believe that the `register` and `identify` commands in the permissions module should already do just that. Please feel free to clarify/reopen if I've misunderstood.

**Comment by Mikaela** [comment]
I understand those to be disabled when services account support is enabled.

I have two NickServ accounts and I wish them to be identified as oneBitBit account without having to `config u` everything twice
