### ISSUE TITLE
misleading announcement for comment edits

### ISSUE THREAD

**Issue by slingamn** [bitbot-irc/bitbot#44]
bitbot assumes that the editor of a comment is the original author, e.g.,

````
(04:48:54 PM) BitBot: (oragono/oragono) [issue #387] slingamn edited a comment on: upgrade message-tags and msgid to non-draft versions - https://git.io/fhNnc
````

whereas the actual editor of that comment, as per the link, is not slingamn but DanielOaks

**Comment by jesopo** [comment]
Had this issue for some other events too and just didn't think fix it for `issue_comment`. Should be fixed as of jesopo/bitbot@120eb031
