### ISSUE TITLE
[github] Check `state` on submitted review hooks

### ISSUE THREAD

**Issue by jwheare** [bitbot-irc/bitbot#46]
Currently the hook text is just "submitted a review on [issuenum]", this can be improved by looking at the review state. State can be stuff like `approved` `changes_requested`
See: https://developer.github.com/v4/enum/pullrequestreviewstate/

Suggested wording:

APPROVED -> "approved changes on [issuenum]"
CHANGES_REQUESTED -> "requested changes on [issuenum]"
COMMENTED -> "commented on [issuenum]"
DISMISSED -> "dismissed a review on [issuenum]"
PENDING -> n/a you won't get hooks for this

**Comment by jesopo** [comment]
Introduced these changes in jesopo/bitbot@4388d17b
