### ISSUE TITLE
Github webhook payload URL

### ISSUE THREAD

**Issue by TehPeGaSuS** [bitbot-irc/bitbot#47]
Maybe I'm just to stupid or dumb 🤷‍♂️
I can't seem to find any docs related to the payload URL that we need to specify in the webhook.
I was just trying to test it with my personal repo in my network and I've completely failed.

**Comment by jesopo** [comment]
When running your own instance of BitBot, you need to enable the REST API first and then the github webhook sits at `<host>:5000/api/github`. This is all very poorly documented at the moment, sorry!

**Comment by jesopo** [comment]
enabling the REST API can be done as either `!botset rest-api on` from an admin account or `> INSERT INTO bot_settings VALUES ('rest-api', 'true');` from a sqlite3 prompt on the bot's database (`databases/bot.db`); both of these need to be followed by a reboot of the bot.

**Comment by TehPeGaSuS** [comment]
I'll check it out and I'll give some feedback.
Seems to be quite a good work :)

**Comment by TehPeGaSuS** [comment]
I've followed the trick to add me as a admin in the bot, and all went well. but when I tried to `botset rest-api on` it said `[!Set] Unknown setting`.
What am I missing here? o.O

**Comment by jesopo** [comment]
oh, just remembered that `rest_api.py` won't be loaded unless you have `tls-api-key` and `tls-api-certificate` set in `bot.conf` - the REST API demands it be run on https.

Generate a self-signed keypair and get those settings in `bot.conf` to point to the filenames of the key and cert and then restart the bot.

**Comment by TehPeGaSuS** [comment]
I must be doing something wrong. I've followed everything, the bot is listening on `<host>:5000`, but if i try to access the `<host>:5000/api/github` i get a **The connection was reset.**

**Comment by jesopo** [comment]
is there an exception in the bot's log?

**Comment by jesopo** [comment]
Yes, there will be an exception in the log because that endpoint is only meant to be hit by github webhooks. You're also going to need to get an API key before using that endpoint for github webhooks....

`/msg <bot> apikey <name> /api/github` and then put the api key it gives you on the end of the webhook endpoint as `?key=<key>`; final url should be: `<host>:5000/api/github?key=<key>`

**Comment by TehPeGaSuS** [comment]
Oh! That explains a lot! It's all up and running! Nice work! :grinning:

**Comment by TehPeGaSuS** [comment]
Btw, does it have any kind of RSS implemented or in the roadmap?

**Comment by jesopo** [comment]
doesn't have support yet but I put some work in to that a while ago and hit some snags. I'll roadmap it if there's want for it

**Comment by TehPeGaSuS** [comment]
Since it's Pytyhon, probably taking a look at Limnoria's RSS thing would help to gather some ideas? ;)

**Comment by jesopo** [comment]
Good idea! Happy if I close this issue?

**Comment by TehPeGaSuS** [comment]
No! I can close it. 😋
Thanks for all the help.

Cheers

**Comment by TehPeGaSuS** [comment]
Btw, I don't know if it's worthy to pin this issue as `1st run help` so people can be aware how to properly do things while you're putting the docs in order?
