### ISSUE TITLE
auto-github cooldown period

### ISSUE THREAD

**Issue by jesopo** [bitbot-irc/bitbot#60]
Fairly simple: add a timeout between automatically turning urls/refs in to info (auto-github)

We can leverage `self.bot.cache.temporary_cache` for this. We still need to `event.eat()` when we decide to not auto-github because otherwise github urls will fall through in to `title.py`.

The cooldown timeout still needs to be decided. 5 mins?

**Comment by jwheare** [comment]
5 mins seems a sensible default. Config option?

**Comment by jesopo** [comment]
:+1:

**Comment by jesopo** [comment]
uses channel config option `auto-github-cooldown`, defaults to disabled. use `!config channel auto-github-cooldown 300` to set it to 300 seconds (5 mins)
