### ISSUE TITLE
error recovery?

### ISSUE THREAD

**Issue by slingamn** [bitbot-irc/bitbot#63]
Currently, BitBot appears to stop entirely in response to most exceptions.

This ticket is to consider possibilities for error recovery:

1. Can some exceptions be logged and passed over?
1. Can some exceptions result in a disconnect/reconnect to the affected network, rather than stopping the entire process?

**Comment by jesopo** [comment]
BitBot only dies when parsing raw data - that's the only thing that the event system calls in an unsafe way.

```
./modules/rest_api.py:                            endpoint).call_unsafe_for_result(params=params,
./modules/commands/__init__.py:            returns = self.events.on("preprocess.command").call_unsafe(
./modules/line_handler/__init__.py:        self.events.on("raw.received").on(line.command).call_unsafe(**kwargs)
./modules/line_handler/__init__.py:        self.events.on("raw.send").on(event["line"].command).call_unsafe(
./src/IRCServer.py:        self.events.on("raw.received").call_unsafe(server=self,
./src/IRCServer.py:            ).call_unsafe(server=self, line=line_parsed, events=line_events)
./src/IRCServer.py:        self.events.on("preprocess.send").call_unsafe(server=self,
./src/IRCServer.py:            self.events.on("raw.send").call_unsafe(server=self,
```

The first 2 are only unsafe because they've got their own try/except. Rest of it is handled in EventManager:

https://github.com/jesopo/bitbot/blob/5299f816af0985abebda2ec031171ebb34d471e2/src/EventManager.py#L212

**Comment by slingamn** [comment]
What about socket errors like #63?

**Comment by jesopo** [comment]
do you mean #59?

**Comment by slingamn** [comment]
Yes, sorry.

**Comment by jesopo** [comment]
I'd rather that kick up an exception - it's something that wouldn't happen unless there was a fundamental issue in the framework. there's a global CRITICAL catch-all here:

https://github.com/jesopo/bitbot/blob/5299f816af0985abebda2ec031171ebb34d471e2/start.py#L110

And I *could* change that to ERROR but I'd prefer that an issue that bad kill the bot

**Comment by slingamn** [comment]
Legit, as long as bad Internet weather can't kill the bot that seems fine.

**Comment by jesopo** [comment]
yeah that's been tested fairly well, I think. if that was the case, I'd be wrapping connect/read/writes better than they already are. ty 👍
