### ISSUE TITLE
Command to get version information (running commit?) out of bitbot

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#84]
I was looking for !version for a more accurate issue, but I didn't find it.

I guess I would expect it to say "Bitbot tagheremaybe 078681eddffb3a29b3136ad12ec01bfa25870124 on `lsb_release -sd` / Python x.y.z" or something similar that could easily be pasted to an issue.

**Comment by jesopo** [comment]
the implementation of this doesn't include the current tag - I'd implement that too if I could figure out how to pull that from `.git` without the use of a library.
