### ISSUE TITLE
Block titling of localhost and local networks (DNS and IP)

### ISSUE THREAD

**Issue by JinnCirce** [bitbot-irc/bitbot#87]
Apparently BitBot correctly titles sites if the DNS points to a localhost address, say `0.0.0.0`, it titles for `localhost` instead of erroring or ignoring, might want to extend the localhost block to that.
Localhost block also not implemented for the most part for localhost IP ranges
- `127.*.*.*`
- `0.*.*.*`

Also maybe add the local network ranges
- `10.*.*.*`
- `192.168.*.*`

to an optional ignore list, as these aren't accessible from the internet, so may also leak services

**Comment by alyx** [comment]
but what if i want to title localhost

**Comment by Jan69** [comment]
> but what if i want to title localhost

then you title `::ffff:7f00:1` ;P
that's too hard to block out

**Comment by JinnCirce** [comment]
> but what if i want to title localhost

you ping `::ffff:7f00:1` ;P

assuming `::1` is blocked, and you have ipv6

**Comment by jesopo** [comment]
this would be resolved by adding more checks here https://github.com/jesopo/bitbot/blob/2885b41bbb8d1e095a62828234d049f815503739/src/utils/http.py#L157

**Comment by AntonMcClure** [comment]
Can this issue be assigned to me

**Comment by jesopo** [comment]
I think this will help us check if an IP is in a "forbidden" range: https://stackoverflow.com/a/51472420/6503979

I'd declare some CONST variables of `IPv4Network`s and `IPv6Network`s outside of `is_localhost` (and actually rename `is_localhost` to `host_allowed` or something) and then check those in the func
