### ISSUE TITLE
Feature request: Allow autovoicing everyone with a delay

### ISSUE THREAD

**Issue by Mikaela** [bitbot-irc/bitbot#88]
> ## I am a chanop and have a spam problem, how can I fix it without affecting Matrix users?
> 
> You have likely attempted to use mode +r or similar which prevents unidentified users from joining the channel also affecting Matrix users. It's not the only way and you may wish to think about some other modes:
> 
> ...
> MODE +m & setting a bot to autovoice everyone with some delay from joining to the channel. This would likely require you to host something by yourself and it would also prevent using of quiet instead of ban, but would be the easiest solution for your users.

from https://github.com/matrix-org/matrix-appservice-irc/wiki/End-user-FAQ#i-am-a-chanop-and-have-a-spam-problem-how-can-i-fix-it-without-affecting-matrix-users and I have found it a nice feature in general when there is a spambot wave on a network.

**Comment by jesopo** [comment]
implemented as of jesopo/bitbot@fc1ed92b4c1636744e7cae4b3e5ae69d515d3535
